import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToasterProvider } from "@/context/ToasterContext";
import ToasterComponent from "@/components/ui/Providers/toaster";
import Navbar from "@/components/fragments/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EventKu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ToasterProvider>
        <head>
          <link
            href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
            rel="stylesheet"
            as="style"
          />
        </head>
        <body className={inter.className}>
          <Navbar />
          {children}
          <ToasterComponent />
        </body>
      </ToasterProvider>
    </html>
  );
}
